In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import sys
import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")

In [2]:
data = pd.read_csv('data/single.csv')

In [3]:
data.head()

WRIST_x   WRIST_y   WRIST_z  THUMB_CMC_x  THUMB_CMC_y  THUMB_CMC_z  \
0  0.508492  0.796419 -0.000384     0.554401     0.677438    -0.150904   
1  0.512087  0.803162 -0.000436     0.547700     0.674914    -0.141695   
2  0.503681  0.794522 -0.000357     0.540451     0.685222    -0.155178   
3  0.522296  0.782431 -0.000211     0.559571     0.664316    -0.159767   
4  0.486943  0.864389 -0.000385     0.560643     0.714334    -0.179251   

   THUMB_MCP_x  THUMB_MCP_y  THUMB_MCP_z  THUMB_IP_x  ...  PINKY_PIP_x  \
0     0.563549     0.560108    -0.302531    0.521770  ...     0.334175   
1     0.549658     0.557700    -0.279454    0.505674  ...     0.343675   
2     0.546599     0.568577    -0.297065    0.511923  ...     0.363206   
3     0.537245     0.522293    -0.265336    0.515844  ...     0.364128   
4     0.580173     0.565320    -0.341146    0.509371  ...     0.231761   

   PINKY_PIP_y  PINKY_PIP_z  PINKY_DIP_x  PINKY_DIP_y  PINKY_DIP_z  \
0     0.577611    -0.375620     0.410385     0.567276    -0.364341   
1     0.575700    -0.344823     0.419720     0.561450    -0.333656   
2     0.550951    -0.389180     0.435049     0.532251    -0.389485   
3     0.601349    -0.360574     0.430683     0.565619    -0.390892   
4     0.654889    -0.421760     0.303781     0.707887    -0.427897   

   PINKY_TIP_x  PINKY_TIP_y  PINKY_TIP_z  CLASS  
0     0.449792     0.533187    -0.341445      1  
1     0.462066     0.529065    -0.307563      1  
2     0.472499     0.492018    -0.373515      1  
3     0.465978     0.516874    -0.398712      1  
4     0.340548     0.732022    -0.412179      1  

[5 rows x 64 columns]

In [4]:
data =data.fillna(0)

In [5]:
data['CLASS'] = data['CLASS'].replace({
    '1':1,
    '2':2,
    '3':3,
    '4':4,
    '5':5,
    '6':6,
    '7':7,
    '8':8,
    '9':9,
    'A':10,
    'B':11,
    'C':12,
    'D':13,
    'E':14,
    'F':15,
    'G':16,
    'H':17,
    'I':18,
    'J':19,
    'K':20,
    'L':21,
    'M':22,
    'N':23,
    'O':24,
    'P':25,
    'Q':26,
    'R':27,
    'S':28,
    'T':29,
    'U':30,
    'V':31,
    'W':32,
    'X':33,
    'Y':34,
    'Z':35
})

In [6]:
X = data.copy()

In [7]:
X

WRIST_x   WRIST_y   WRIST_z  THUMB_CMC_x  THUMB_CMC_y  THUMB_CMC_z  \
0      0.508492  0.796419 -0.000384     0.554401     0.677438    -0.150904   
1      0.512087  0.803162 -0.000436     0.547700     0.674914    -0.141695   
2      0.503681  0.794522 -0.000357     0.540451     0.685222    -0.155178   
3      0.522296  0.782431 -0.000211     0.559571     0.664316    -0.159767   
4      0.486943  0.864389 -0.000385     0.560643     0.714334    -0.179251   
...         ...       ...       ...          ...          ...          ...   
17277  0.499351  0.779465 -0.000266     0.607964     0.679596     0.023837   
17278  0.485918  0.800466 -0.000150     0.600437     0.674523     0.050803   
17279  0.503772  0.768210 -0.000221     0.614549     0.686530     0.023255   
17280  0.521569  0.805201 -0.000197     0.470532     0.747638     0.044567   
17281  0.475984  0.790486 -0.000197     0.601566     0.696751     0.046997   

       THUMB_MCP_x  THUMB_MCP_y  THUMB_MCP_z  THUMB_IP_x  ...  PINKY_PIP_x  \
0         0.563549     0.560108    -0.302531    0.521770  ...     0.334175   
1         0.549658     0.557700    -0.279454    0.505674  ...     0.343675   
2         0.546599     0.568577    -0.297065    0.511923  ...     0.363206   
3         0.537245     0.522293    -0.265336    0.515844  ...     0.364128   
4         0.580173     0.565320    -0.341146    0.509371  ...     0.231761   
...            ...          ...          ...         ...  ...          ...   
17277     0.621648     0.549566    -0.031266    0.576181  ...     0.372192   
17278     0.633013     0.539576    -0.001887    0.575582  ...     0.343868   
17279     0.627926     0.566838    -0.017984    0.577039  ...     0.357098   
17280     0.440813     0.619145     0.019861    0.432410  ...     0.479787   
17281     0.640941     0.576457     0.010070    0.598926  ...     0.349892   

       PINKY_PIP_y  PINKY_PIP_z  PINKY_DIP_x  PINKY_DIP_y  PINKY_DIP_z  \
0         0.577611    -0.375620     0.410385     0.567276    -0.364341   
1         0.575700    -0.344823     0.419720     0.561450    -0.333656   
2         0.550951    -0.389180     0.435049     0.532251    -0.389485   
3         0.601349    -0.360574     0.430683     0.565619    -0.390892   
4         0.654889    -0.421760     0.303781     0.707887    -0.427897   
...            ...          ...          ...          ...          ...   
17277     0.506430    -0.167713     0.409741     0.546717    -0.094009   
17278     0.503991    -0.113871     0.388548     0.542132    -0.046105   
17279     0.510633    -0.153518     0.390716     0.550789    -0.082246   
17280     0.451270    -0.149601     0.506812     0.400481    -0.158573   
17281     0.517314    -0.100352     0.389310     0.559197    -0.038912   

       PINKY_TIP_x  PINKY_TIP_y  PINKY_TIP_z  CLASS  
0         0.449792     0.533187    -0.341445      1  
1         0.462066     0.529065    -0.307563      1  
2         0.472499     0.492018    -0.373515      1  
3         0.465978     0.516874    -0.398712      1  
4         0.340548     0.732022    -0.412179      1  
...            ...          ...          ...    ...  
17277     0.419175     0.594607    -0.062159     31  
17278     0.417052     0.595180    -0.015246     31  
17279     0.400652     0.597682    -0.055214     31  
17280     0.533713     0.341693    -0.202990     31  
17281     0.411970     0.613121    -0.013635     31  

[17282 rows x 64 columns]

In [8]:
y = X.pop('CLASS')

In [9]:
y.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12, 18, 21, 24, 30, 31],
      dtype=int64)

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,stratify=y,test_size=0.3)

In [12]:
from sklearn.linear_model import LogisticRegression
lmodel = LogisticRegression(max_iter=120)
lmodel.fit(X_train,y_train)

LogisticRegression(max_iter=120)

In [13]:
lmodel.predict(X_test)

array([ 1,  1, 21, ..., 24, 18,  6], dtype=int64)

In [14]:
lmodel.score(X_test,y_test)

0.989778206364513

In [15]:
from sklearn import svm
clf = svm.SVC(kernel='linear') # Linear Kernel
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [16]:
y_pred = clf.predict(X_test)

In [17]:
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9957569913211186


In [18]:
from sklearn.datasets import load_iris
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt
sc_X = StandardScaler()
X_trainscaled=sc_X.fit_transform(X_train)
X_testscaled=sc_X.transform(X_test)
MLPclf = MLPClassifier(hidden_layer_sizes=(256,128,64,32),activation="relu",random_state=1).fit(X_trainscaled, y_train)
y_pred=MLPclf.predict(X_testscaled)


In [19]:
print(MLPclf.score(X_testscaled, y_test))

0.997685631629701


In [20]:
testC = pd.read_csv('output/C_0.csv')

In [20]:
lmodel.predict(testC)

array([12], dtype=int64)

In [21]:
clf.predict(testC)

array([12], dtype=int64)

In [22]:
MLPclf.predict(testC)

array([12], dtype=int64)

In [23]:
testV = pd.read_csv('output/V.csv')

In [24]:
lmodel.predict(testV)

array([31], dtype=int64)

In [25]:
clf.predict(testV)

array([31], dtype=int64)

In [26]:
import joblib
joblib.dump(clf,'models/single_svm.pkl')


['models/single_svm.pkl']

In [27]:
joblib.dump(lmodel,'models/single_regr.pkl')

['models/single_regr.pkl']

In [28]:
joblib.dump(MLPclf,'models/single_mlp.pkl')

['models/single_mlp.pkl']

In [29]:
alphabets = ['0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']

In [30]:
clf.predict(testV)

array([31], dtype=int64)

In [31]:
print(type(clf.predict(testV)))

<class 'numpy.ndarray'>


In [32]:
x = clf.predict(testV)

In [33]:
x.item(0)

31

In [34]:
alphabets[clf.predict(testV).item(0)]

'V'

In [35]:
test1 = pd.read_csv('output/1.csv')

In [36]:
test1

WRIST_x_0  WRIST_y_0  WRIST_z_0  THUMB_CMC_x_0  THUMB_CMC_y_0  \
0    0.50852   0.790683  -0.000406       0.544076       0.681068   

   THUMB_CMC_z_0  THUMB_MCP_x_0  THUMB_MCP_y_0  THUMB_MCP_z_0  THUMB_IP_x_0  \
0      -0.167377       0.545776       0.570889      -0.317149      0.503694   

   ...  PINKY_MCP_z_0  PINKY_PIP_x_0  PINKY_PIP_y_0  PINKY_PIP_z_0  \
0  ...      -0.265049        0.35401       0.552125      -0.367444   

   PINKY_DIP_x_0  PINKY_DIP_y_0  PINKY_DIP_z_0  PINKY_TIP_x_0  PINKY_TIP_y_0  \
0        0.42842       0.528749      -0.366115       0.467233       0.489294   

   PINKY_TIP_z_0  
0      -0.346806  

[1 rows x 63 columns]

In [37]:
clf.predict(test1)

array([1], dtype=int64)