In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import sys
import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")

In [3]:
data = pd.read_csv('data/both.csv')

In [4]:
data.head()

WRIST_x_0  WRIST_y_0  WRIST_z_0  THUMB_CMC_x_0  THUMB_CMC_y_0  \
0   0.842034   0.615982   0.000073       0.786678       0.532512   
1   0.845142   0.617416   0.000078       0.790946       0.533602   
2   0.848125   0.608161  -0.000129       0.783306       0.526929   
3   0.831402   0.603912   0.000120       0.752286       0.527703   
4   0.148650   0.596327   0.000015       0.219593       0.512971   

   THUMB_CMC_z_0  THUMB_MCP_x_0  THUMB_MCP_y_0  THUMB_MCP_z_0  THUMB_IP_x_0  \
0       0.003552       0.714849       0.485646      -0.047130      0.651691   
1      -0.000602       0.723400       0.489584      -0.057440      0.666784   
2       0.001680       0.700106       0.480671      -0.051200      0.631718   
3      -0.009510       0.679841       0.489973      -0.072688      0.625047   
4      -0.028349       0.309556       0.445312      -0.113296      0.374157   

   ...  PINKY_PIP_x_1  PINKY_PIP_y_1  PINKY_PIP_z_1  PINKY_DIP_x_1  \
0  ...       0.239249       0.683961      -0.434966       0.242846   
1  ...       0.236464       0.687991      -0.423164       0.246515   
2  ...       0.241202       0.684458      -0.417048       0.241420   
3  ...       0.250462       0.720215      -0.435492       0.239459   
4  ...       0.826576       0.643474      -0.411244       0.766859   

   PINKY_DIP_y_1  PINKY_DIP_z_1  PINKY_TIP_x_1  PINKY_TIP_y_1  PINKY_TIP_z_1  \
0       0.691651      -0.449079       0.239898       0.683380      -0.473893   
1       0.693188      -0.418437       0.243938       0.688330      -0.426309   
2       0.688010      -0.432026       0.236321       0.673273      -0.459042   
3       0.712629      -0.403031       0.220165       0.685930      -0.394610   
4       0.673322      -0.442801       0.710410       0.684412      -0.465401   

   CLASS  
0      A  
1      A  
2      A  
3      A  
4      A  

[5 rows x 127 columns]

In [5]:
data.tail()
data = data.fillna(0)

In [6]:
data['CLASS'] = data['CLASS'].replace({
    '1':1,
    '2':2,
    '3':3,
    '4':4,
    '5':5,
    '6':6,
    '7':7,
    '8':8,
    '9':9,
    'A':10,
    'B':11,
    'C':12,
    'D':13,
    'E':14,
    'F':15,
    'G':16,
    'H':17,
    'I':18,
    'J':19,
    'K':20,
    'L':21,
    'M':22,
    'N':23,
    'O':24,
    'P':25,
    'Q':26,
    'R':27,
    'S':28,
    'T':29,
    'U':30,
    'V':31,
    'W':32,
    'X':33,
    'Y':34,
    'Z':35
})

In [7]:
X=data.copy()

In [8]:
y = X.pop('CLASS')

In [9]:
y.head()

0    10
1    10
2    10
3    10
4    10
Name: CLASS, dtype: int64

In [10]:
y.unique()

array([10, 11, 13, 14, 15, 16, 17, 19, 20, 22, 23, 25, 26, 27, 28, 29, 32,
       33, 34, 35], dtype=int64)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,stratify=y,test_size=0.3)

In [12]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=120)
model.fit(X_train,y_train)

LogisticRegression(max_iter=120)

In [13]:
model.predict(X_test)

array([15, 11, 28, ..., 29, 11, 17], dtype=int64)

In [14]:
model.score(X_test,y_test)

0.984759671746776

In [15]:
from sklearn import svm

In [16]:
#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

In [17]:
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [18]:
y_pred = clf.predict(X_test)

In [19]:
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9948710433763188


In [20]:
testA2 = pd.read_csv('output/A_2.csv')

In [22]:
clf.predict(testA2)

array([10], dtype=int64)

In [20]:
from sklearn.datasets import load_iris
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt

In [21]:
sc_X = StandardScaler()
X_trainscaled=sc_X.fit_transform(X_train)
X_testscaled=sc_X.transform(X_test)

In [22]:
MLPclf = MLPClassifier(hidden_layer_sizes=(256,128,64,32),activation="relu",random_state=1).fit(X_trainscaled, y_train)
y_pred=MLPclf.predict(X_testscaled)


In [23]:
print(MLPclf.score(X_testscaled, y_test))

0.9956037514654161


In [24]:
testA = pd.read_csv('output/A_2.csv')
testA = testA.fillna(0)

In [25]:
clf.predict(testA)

array([10], dtype=int64)

In [26]:
MLPclf.predict(testA)

array([10], dtype=int64)

In [27]:
model.predict(testA)

array([10], dtype=int64)

In [28]:
import joblib
joblib.dump(model,'models/both_regr.pkl')

['models/both_regr.pkl']

In [29]:
joblib.dump(clf,'models/both_svm.pkl')

['models/both_svm.pkl']

In [30]:
joblib.dump(MLPclf,'models/both_mlp.pkl')

['models/both_mlp.pkl']

In [1]:
testA2 = pd.read_csv('output/A_2.csv')

NameError: name 'pd' is not defined